//go:build ignore

package main

import (
	"fmt"

	"github.com/unixdj/qr/coding"
)

var sizeClass = [7]coding.Version{
	coding.M1, coding.M2, coding.M3, coding.M4, 9, 26, 40,
}

func main() {
	fmt.Print(`// generated by go run gen.go; DO NOT EDIT

package split

// Maximum data bits for each error correction level and size class.
var sizeLimit = [4][7]int{
`)
	for i := coding.L; i <= coding.H; i++ {
		fmt.Printf("\t%s: {", i)
		pref := ""
		for j := 0; j < 7; j++ {
			fmt.Print(pref, sizeClass[j].DataBits(i))
			pref = ", "
		}
		fmt.Println("},")
	}
	fmt.Println("}")
}
