// generated by go run gen.go; DO NOT EDIT

package split

// Maximum data bits for each error correction level and size class.
var sizeLimit = [4][7]int{
	L: {20, 40, 84, 128, 1856, 10960, 23648},
	M: {0, 32, 68, 112, 1456, 8496, 18672},
	Q: {0, 0, 0, 80, 1056, 6032, 13328},
	H: {0, 0, 0, 0, 800, 4768, 10208},
}
