//go:build none

package main

import (
	"bufio"
	"fmt"
	"log"
	"net/http"
	"strconv"
	"strings"
)

func main() {
	const url = "https://gitlab.freedesktop.org/xorg/app/rgb/-/raw/master/rgb.txt"
	res, err := http.Get(url)
	if err != nil {
		log.Fatalf("%q: Get: %v", url, err)
	}
	defer res.Body.Close()
	fmt.Println(`// generated by go run gen.go | gofmt; DO NOT EDIT

package main

var rgb = map[string]rgba{`)
	sc := bufio.NewScanner(res.Body)
	for line := 1; sc.Scan(); line++ {
		s := sc.Text()
		var f [3]byte
		for i := range f {
			var t string
			t, s = cut(s)
			n, err := strconv.ParseUint(t, 10, 8)
			if err != nil {
				log.Fatalf("parse error on line %d: %s", line, t)
			}
			f[i] = byte(n)
		}
		if s == "" {
			log.Fatalln("parse error on line %d", line)
		}
		if 'A' <= s[0] && s[0] <= 'Z' {
			continue
		}
		fmt.Printf("\t%q: {%#02x, %#02x, %#02x, 0xff},\n",
			strings.ReplaceAll(s, " ", ""), f[0], f[1], f[2])
	}
	if err := sc.Err(); err != nil {
		log.Fatalln(err)
	}
	fmt.Println(`}`)
}

func cut(s string) (string, string) {
	s = strings.TrimSpace(s)
	i := strings.IndexAny(s, " \t")
	if i == -1 {
		return s, s
	}
	return s[:i], strings.TrimSpace(s[i:])
}
